#Minecraft server properties
#Mon Jul 13 00:19:27 UTC 2026
generator-settings=
op-permission-level=4
allow-nether=true
level-name=world
enable-query=false
allow-flight=false
announce-player-achievements=true
server-port=25568
level-type=DEFAULT
enable-rcon=false
force-gamemode=false
level-seed=
server-ip=
max-build-height=256
spawn-npcs=true
white-list=false
spawn-animals=true
hardcore=false
online-mode=false
resource-pack=
pvp=true
difficulty=2
enable-command-block=true
gamemode=0
player-idle-timeout=0
max-players=123
max-tick-time=-1
spawn-monsters=true
view-distance=10
generate-structures=true
pause-when-empty-seconds=0
motd=The NTNH Digamma server
